# Generated by Django 2.2.1 on 2020-01-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='知名高校', max_length=10, verbose_name='机构标签'),
        ),
    ]
